version: '3.8'
services:
  app:
    build: .
    ports:
      - '4000:4000'
    env_file: .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
volumes:
  pgdata:
